<div id="modal">
    <div class="modal-body-content">
        <h2 id="modal-title"></h2>
        <p id="modal-content"></p>
    </div>
</div>

<div id="modal-popup">
    <div class="modal-body-content">
        <p id="modal-popup-content"></p>
    </div>
</div>

<script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "modal_overlay": {
                            "component": "Modules_Banner/js/modal_overlay"
                        }
                     }
                }
            }
        }
    </script>
