<div id="modal">
    <div class="modal-body-content">
        <h2 id="modal-title"></h2>
        <p id="modal-content"></p>
    </div>
</div>

<div id="modal-popup">
    <div class="modal-body-content">
        <p id="modal-popup-content"></p>
    </div>
</div>

<script type="text/javascript">
    require([
        "jquery",
        "Magento_Ui/js/modal/modal"
    ],function($, modal) {
        var popup;
        $.ajax({
            url:  'http://magento2.local/rest/all/V1/banner/banners/3',
            type: 'get',
            data: {},
            success: function(response){
                console.log(response);
                $("#modal-title").html(response.title);
                $("#modal-content").html(response.text);
                $("#modal-popup-content").html(response.popel);

                var options = {
                    type: 'popup',
                    responsive: true,
                    title: response.title
                };

                popup = modal(options, $('#modal-popup'));
                $("#modal").click(function() {
                    $('#modal-popup').modal('openModal');
                });
            },
            error: function(){

            }
        });

    });
</script>
